vqgan_ckpt: /home/fi/GY/medicaldiffusion/checkpoints/vq_gan/DEFAULT/gy/lightning_logs/version_0/checkpoints/epoch=298-step=300000-10000-train/recon_loss=0.07.ckpt

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 32
diffusion_depth_size: 32
diffusion_num_channels: 8
dim_mults: [1,2,4,8]
results_folder: /home/fi/GY/medicaldiffusion/checkpoints/ddpm/
results_folder_postfix: 'gy'
load_milestone: False

batch_size: 10
num_workers: 10
logger: wandb
objective: pred_x0
save_and_sample_every: 1000
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 300 # number of steps
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 700000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 0

